image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  AWS_REGION: ap-south-1
  AWS_ACCOUNT_ID: 703671925616
  ECR_REPOSITORY: angular-frontend
  ECR_REGISTRY: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  IMAGE_TAG: $ECR_REGISTRY/$ECR_REPOSITORY:latest

stages:
  - build_and_push
  - deploy

build_and_push:
  stage: build_and_push
  script:
    - echo "Installing AWS CLI..."
    - apk add --no-cache aws-cli
    - echo "AWS CLI version:" && aws --version

    - echo "Logging into ECR..."
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

    - echo "Building Docker image..."
    - docker build -t "$IMAGE_TAG" .

    - echo "Pushing Docker image to ECR..."
    - docker push "$IMAGE_TAG"


deploy-to-eks:
  stage: deploy
  image: amazonlinux:2
  before_script:
    - yum install -y unzip curl git tar gzip python3 pip
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip && ./aws/install
    - curl -LO https://dl.k8s.io/release/v1.32.3/bin/linux/amd64/kubectl
    - chmod +x kubectl && mv kubectl /usr/local/bin/
    - kubectl version --client
    - aws eks --region "$AWS_REGION" update-kubeconfig --name "$CLUSTER_NAME"
  script:
    - echo "Deploying to EKS..."
    - kubectl apply --validate=false -f k8s/
    - kubectl get all

 