image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  AWS_REGION: ap-south-1
  AWS_ACCOUNT_ID: 703671925616
  ECR_REPOSITORY: angular-frontend
  ECR_REGISTRY: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
  IMAGE_TAG: ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest

before_script:
  - apk add --no-cache aws-cli
  - aws --version
  - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

stages:
  - build_and_push

build_and_push:
  stage: build_and_push
  script:
    - echo "Building image: $IMAGE_TAG"
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
